MODEL:
  config:
    layers:
    - class_name: Dense
      config:
        activation: tanh
        batch_input_shape: !!python/tuple
        - null
        - 108 # number of features
        trainable: true
        units: 10
    - class_name: Dense
      config:
        activation: tanh
        trainable: true
        units: 10
    - class_name: Dense
      config:
        activation: tanh
        trainable: true
        units: 2
MODEL_PATH: 'notebooks/saved_model/'
OPTIMIZER:
  learning_rate: 0.3
LOSS:
  class_name: 'SparseCategoricalCrossentropy'
  from_logits: True
METRICS:
  - 'accuracy'
  - 'mse'
FIT:
  epochs: 10


  

