MODEL:
  GRAPH:
    config:
      layers:
      - class_name: Dense
        config:
          activation: tanh
          batch_input_shape: !!python/tuple
          - 108 # number of features
          trainable: true
          units: 10
      - class_name: Dense
        config:
          activation: tanh
          trainable: true
          units: 10
      - class_name: Dense
        config:
          activation: tanh
          trainable: true
          units: 2 # number of classes
  OPTIMIZER:
    optimizer: !!python/name:tensorflow.keras.optimizers.SGD
    kwargs:
      learning_rate: 0.15
  DP_OPTIMIZER:
    optimizer: !!python/name:tensorflow_privacy.privacy.optimizers.dp_optimizer.DPGradientDescentGaussianOptimizer
    kwargs:
      learning_rate: 0.15
      noise_multiplier: 1.5
      l2_norm_clip: 1.5
  LOSS:
    loss: !!python/name:tensorflow.keras.losses.SparseCategoricalCrossentropy
    kwargs:
      from_logits: True
  METRICS:
    - accuracy
    - mse

FIT:
  epochs: 10

FIT_DP:
  epochs: 10