MODEL:
  config:
    layers:
    - class_name: Dense
      config:
        activation: tanh
        batch_input_shape: !!python/tuple
        - null
        - 108 # number of features
        trainable: true
        units: 10
    - class_name: Dense
      config:
        activation: tanh
        trainable: true
        units: 10
    - class_name: Dense
      config:
        activation: tanh
        trainable: true
        units: 2 # number of classes
MODEL_PATH: notebooks/saved_model/
OPTIMIZER:
  learning_rate: 0.3
DP_OPTIMIZER:
  learning_rate: 0.3
  noise_multiplier: 1.3
  l2_norm_clip: 1.5
  num_microbatches: 1
LOSS:
  class_name: SparseCategoricalCrossentropy
  from_logits: True
METRICS:
  - accuracy
  - mse
FIT:
  epochs: 10