name: ci

on:
  push:
    branches:
    - master
    - actions

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip and project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade setuptools
        pycodestyle --version
        #pip install -r requirements-dev.txt

    - name: Run pytest
      run: |
        pip install pytest
        #python -m pytest -m "not slow"

    - name: Create wheel-cython distribution
      run: |
        #python setup.py install_egg_info
        #pip install -e .
        #pip install pycodestyle==2.6.0
        python setup.py bdist_wheel
        #python setup.py bdist --cythonize 
