# https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
# curl \
#  -X POST \
#  -H "Accept: application/vnd.github.v3+json" \
#  https://api.github.com/repos/octocat/hello-world/actions/workflows/42/dispatches \
#  -d '{"ref":"ref"}'

name: test_pytest

on:
  workflow_dispatch:
    inputs:
      source_branch: 
        description: 'Which branch should be used (default: develop)'
        default: 'develop'
        required: true

jobs:

  job_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.source_branch }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip and setuptools dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools-cythonize==1.0.5

    - name: Install project dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run pytest
      run: |
        pip install pytest
        python -m pytest -m "not slow"
